services:

  mysql:

    image: mysql:8.4

    container_name: wms-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse_management

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .

    container_name: warehouse-management

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

volumes:

  mysql-data:
