spring:
  application:
    name: warehouse-management

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/warehouse_management}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha

    api-docs:
      path: /api-docs



jwt:
  secret: 0123456789012345678901234567890123456789012345678901234567890123
  expiration: 86400000

logging:
  level:
    org.springframework.security: TRACE

server:
  port: 8080